### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by dennorske** [leHeix/cockmmand#1]
Hello dear sir.

Your command "processor" is not working as described. I'd rather call it an alias for strcmp.

**Some benchmarks;** 
Cockmand (STRCMP): 10000 commands took ~76 ms to complete
ZCMD: 10000 commands took ~4 ms

Source of data I used (https://gist.github.com/PatrickGTR/8889699)
https://gist.github.com/PatrickGTR/8889699

I think you can put cockman up in vageene. Thanks

**Comment by neiam00** [comment]
bullshit
